// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEpZitxs8RsQ23MjTyfOWzPAWQldZm_J0',
    appId: '1:901531000542:web:0e0c14b9f61eefd60d2c4f',
    messagingSenderId: '901531000542',
    projectId: 'xzofitness-35359',
    authDomain: 'xzofitness-35359.firebaseapp.com',
    databaseURL: 'https://xzofitness-35359-default-rtdb.firebaseio.com',
    storageBucket: 'xzofitness-35359.firebasestorage.app',
    measurementId: 'G-3H4P6HKRE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRnU1Fjf4Us77SLz634qkov9m8djs6dAI',
    appId: '1:901531000542:android:8cf97b38965aa67d0d2c4f',
    messagingSenderId: '901531000542',
    projectId: 'xzofitness-35359',
    databaseURL: 'https://xzofitness-35359-default-rtdb.firebaseio.com',
    storageBucket: 'xzofitness-35359.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAriXtUFd0HP8mPH-WneGzS0b4cp4342yo',
    appId: '1:901531000542:ios:012c920fbc315d820d2c4f',
    messagingSenderId: '901531000542',
    projectId: 'xzofitness-35359',
    databaseURL: 'https://xzofitness-35359-default-rtdb.firebaseio.com',
    storageBucket: 'xzofitness-35359.firebasestorage.app',
    iosClientId: '901531000542-tdukdn9v3cs9pptfquv0u7bh18m5957m.apps.googleusercontent.com',
    iosBundleId: 'com.example.turathi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAriXtUFd0HP8mPH-WneGzS0b4cp4342yo',
    appId: '1:901531000542:ios:012c920fbc315d820d2c4f',
    messagingSenderId: '901531000542',
    projectId: 'xzofitness-35359',
    databaseURL: 'https://xzofitness-35359-default-rtdb.firebaseio.com',
    storageBucket: 'xzofitness-35359.firebasestorage.app',
    iosClientId: '901531000542-tdukdn9v3cs9pptfquv0u7bh18m5957m.apps.googleusercontent.com',
    iosBundleId: 'com.example.turathi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEpZitxs8RsQ23MjTyfOWzPAWQldZm_J0',
    appId: '1:901531000542:web:391940d8f7f9712a0d2c4f',
    messagingSenderId: '901531000542',
    projectId: 'xzofitness-35359',
    authDomain: 'xzofitness-35359.firebaseapp.com',
    databaseURL: 'https://xzofitness-35359-default-rtdb.firebaseio.com',
    storageBucket: 'xzofitness-35359.firebasestorage.app',
    measurementId: 'G-BX99T577GX',
  );

}